export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST';
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS';
export const GET_FEATURES_FALIURE = 'GET_FEATURES_FALIURE';
export const UPDATE_FEATURE_LIST = 'UPDATE_FEATURE_LIST';
export const VIN_NUMBER = 'VIN_NUMBER';
export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FALIURE = 'UPLOAD_IMAGE_FALIURE';
